// <auto-generated />
using System;
using GhBrandingBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GhBrandingBackend.Migrations
{
    [DbContext(typeof(RegistrosContext))]
    [Migration("20230404030234_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GhBrandingBackend.Models.Registros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<TimeSpan>("HorasDia")
                        .HasColumnType("timespan");

                    b.Property<DateTime>("RegistroFinal")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("RegistroInicial")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Registros", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
